# -*- python -*-
Import('env')

py = env.Install('fcli/', env.Glob('py/*'))
common = env.Install('fcli/', env.Glob('#src/common/*'))

fc = env.fcli_upload_function(
    'updater.log', 'fcli/',
    handler='updater.main',
    service='delivery-demo',
    function='flywireUpdater')
env.Depends(fc, [py, common])
env.Default(fc)
