# -*- python -*-
Import('env')

py = env.Install('fcli/', env.Glob('py/*'))

fc = env.fcli_update_function(
    'updater.log', 'fcli/',
    handler='updater.main',
    service='delivery-demo',
    function='flywireUpdater')
env.Depends(fc, [py])
env.Alias('FC', fc)
