# -*- python -*-
Import('env')

py = env.Install('fcli/', 'py/accumulator.py')
common = env.Install('fcli/', env.Glob('#src/common/*'))

fc = env.fcli_upload_function(
    'accumulator.log', 'fcli/',
    handler='accumulator.main',
    service='delivery-demo',
    function='accumulator')
env.Depends(fc, [py, common])
env.Default(fc)
