# -*- python -*-
Import('env')

py = env.Install('fcli/', 'py/flywire.py')
common = env.Install('fcli/', env.Glob('#src/common/*'))

fc = env.fcli_upload_function(
    'flywire.log', 'fcli/',
    handler='flywire.main',
    service='delivery-demo',
    function='flywire')
env.Depends(fc, [py, common])
env.Default(fc)
